spring:
  application:
    name: accommodation-2306211231-be

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  profiles:
    active: 'dev'

  jpa:
    hibernate:
      ddl-auto: create-drop
      
    # Uncomment if you want SQL logging (previously added during debugging)
    # show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true

server:
  port: 8081
