package apap.ti._5.accommodation_2306211231_be.restdto.response.accommodationbooking;

import java.time.LocalDateTime;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AccommodationReviewDTO {
    // optional when creating; generated by backend
    private String reviewId;

    @NotBlank
    private String propertyId;

    @NotBlank
    private String customerUsername;

    @NotBlank
    private String bookingId;

    @NotNull
    @Min(1)
    @Max(5)
    private Integer overallRating;

    @NotNull
    @Min(1)
    @Max(5)
    private Integer cleanlinessRating;

    @NotNull
    @Min(1)
    @Max(5)
    private Integer facilityRating;

    @NotNull
    @Min(1)
    @Max(5)
    private Integer serviceRating;

    @NotNull
    @Min(1)
    @Max(5)
    private Integer valueRating;

    private String comment;

    // optional; filled by backend on creation
    private LocalDateTime createdDate;
}
