apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travel-apap-accommodation-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  # ingressClassName: traefik
  rules:
    - host: 2306211231-be.hafizmuh.site
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: travel-apap-accommodation-be-service
                port:
                  number: 80